spring.application.name=sonora
server.port=8081
spring.config.import=optional:file:.env[.properties]
#spring.profiles.active=test
spring.datasource.url=${PSQLDB_URL}
spring.datasource.username=${PSQLDB_USERNAME}
spring.datasource.password=${PSQLDB_PASSWORD}
spring.web.error.include-stacktrace=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt_secret=${JWT_SECRET}
#E usado para colocar o sql no console e observar a formatação e o que esta fazendo
#
#Email
#spring.mail.host=
#spring.mail.port=
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.transport.protocol=smtp
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.auth=true
