<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.senior.com.br/my_domain/my_service"
    targetNamespace="http://www.senior.com.br/my_domain/my_service"
    elementFormDefault="qualified">
    
    <xsd:attribute name="deprecated" type="xsd:string" default=""/>
    <xsd:attribute name="anonymous" type="xsd:boolean" default="false"/>
    
    <xsd:attribute name="i18n" type="xsd:boolean" default="false"/>
    
    <!-- Public types -->
    <xsd:complexType name="recordRegistroProducao">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="peca" type="peca" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="funcionario" type="funcionario" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="maquina" type="maquina" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="dataInicio" type="xsd:dateTime" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="dataFinal" type="xsd:dateTime" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="retornoRelatorio">
        <xsd:sequence>
            <!-- collection wrapper for maquinaTrabalhando -->
            <xsd:element name="maquinaTrabalhando" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="item" type="maquinaTrabalhando" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="pecaMortas"  minOccurs="1" maxOccurs="1"  readOnly="false">
            <xsd:simpleType>
            	<xsd:restriction base="xsd:long">
            		<xsd:minInclusive value="0" />
            	</xsd:restriction>
            </xsd:simpleType>
            </xsd:element>
            <!-- collection wrapper for pecaFuncionario -->
            <xsd:element name="pecaFuncionario" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="item" type="pecaFuncionario" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="maquinaTrabalhando">
        <xsd:sequence>
            <xsd:element name="maquina" type="maquina" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="horas"  minOccurs="1" maxOccurs="1"  readOnly="false">
            <xsd:simpleType>
            	<xsd:restriction base="xsd:long">
            		<xsd:minInclusive value="0" />
            	</xsd:restriction>
            </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="pecaFuncionario">
        <xsd:sequence>
            <xsd:element name="peca" type="peca" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="funcionario" type="funcionario" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="retornoAtualizarStatus">
        <xsd:sequence>
            <xsd:element name="mensagemRetorno" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="id" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="contemErro" type="xsd:boolean" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="tipoRelatorio">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="PERIODO"/>
            <xsd:enumeration value="MENSAL"/>
            <xsd:enumeration value="ANUAL"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="statusPeca">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="PENDENTE"/>
            <xsd:enumeration value="PROCESSO"/>
            <xsd:enumeration value="FINALIZADO"/>
            <xsd:enumeration value="MORTA"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="statusMaquina">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ATIVO"/>
            <xsd:enumeration value="MANUTENCAO"/>
            <xsd:enumeration value="INATIVO"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="turnoFuncionario">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="PRIMEIRO"/>
            <xsd:enumeration value="SEGUNDO"/>
            <xsd:enumeration value="TERCEIRO"/>
            <xsd:enumeration value="DIURNO"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:complexType name="peca">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:uuid" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="nome"  minOccurs="1" maxOccurs="1"  readOnly="false">
            <xsd:simpleType>
            	<xsd:restriction base="xsd:string">
            		<xsd:maxLength value="100" />
            	</xsd:restriction>
            </xsd:simpleType>
            </xsd:element>
            <xsd:element name="codigoDesenho"  minOccurs="1" maxOccurs="1"  readOnly="false">
            <xsd:simpleType>
            	<xsd:restriction base="xsd:string">
            		<xsd:maxLength value="50" />
            	</xsd:restriction>
            </xsd:simpleType>
            </xsd:element>
            <xsd:element name="tempoEstimadoMinutos" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="status" type="statusPeca" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="valor" type="xsd:decimal" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="motivoPerda" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="funcionario">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:uuid" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="nome" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="matricula"  minOccurs="1" maxOccurs="1"  readOnly="false">
            <xsd:simpleType>
            	<xsd:restriction base="xsd:string">
            		<xsd:maxLength value="20" />
            	</xsd:restriction>
            </xsd:simpleType>
            </xsd:element>
            <xsd:element name="cargo" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="turno" type="turnoFuncionario" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="ativo" type="xsd:boolean" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="username" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="maquina">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:uuid" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="nome" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="status" type="statusMaquina" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="registroProducao">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:uuid" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="peca" type="peca" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="funcionario" type="funcionario" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="maquina" type="maquina" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="dataInicio" type="xsd:dateTime" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="dataFinal" type="xsd:dateTime" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="userNotificationKind">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Operational"/>
            <xsd:enumeration value="Management"/>
            <xsd:enumeration value="News"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="userNotificationPriority">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Error"/>
            <xsd:enumeration value="Alert"/>
            <xsd:enumeration value="None"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:complexType name="notifyUserEventPayload">
        <xsd:sequence>
            <xsd:element name="notificationClass" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="notificationOrigin" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="notificationKind" type="userNotificationKind" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="notificationPriority" type="userNotificationPriority" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="notificationSubject" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="notificationContent" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="sourceDomain" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="sourceService" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="destinationUser" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="link" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="eventEmailFormat">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="HTML"/>
            <xsd:enumeration value="PLAIN_TEXT"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:complexType name="emailNotifyUserEventPayload">
        <xsd:complexContent>
            <xsd:extension base="notifyUserEventPayload">
                <xsd:sequence>
                    <xsd:element name="from" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                    </xsd:element>
                    <!-- collection wrapper for sendTo -->
                    <xsd:element name="sendTo" minOccurs="0" maxOccurs="1">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="item" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="format" type="eventEmailFormat" minOccurs="0" maxOccurs="1"  readOnly="false">
                    </xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:complexType name="pushNotifyUserEventPayload">
        <xsd:complexContent>
            <xsd:extension base="notifyUserEventPayload">
                <xsd:sequence>
                    <xsd:element name="applicationId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                    </xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:complexType name="blobReference">
        <xsd:sequence>
            <xsd:element name="domainName" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="serviceName" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="targetObjectId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="targetCopyId" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="basicErrorPayload">
        <xsd:sequence>
            <xsd:element name="message" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="errorCode" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="fieldType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="BINARY"/>
            <xsd:enumeration value="BOOLEAN"/>
            <xsd:enumeration value="DATE"/>
            <xsd:enumeration value="DATETIME"/>
            <xsd:enumeration value="LOCALDATETIME"/>
            <xsd:enumeration value="DOUBLE"/>
            <xsd:enumeration value="ENUM"/>
            <xsd:enumeration value="INTEGER"/>
            <xsd:enumeration value="MONEY"/>
            <xsd:enumeration value="STRING"/>
            <xsd:enumeration value="TIME"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="fileFormat">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="CSV"/>
            <xsd:enumeration value="FLAT"/>
            <xsd:enumeration value="JSON"/>
            <xsd:enumeration value="XML"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="hookFunction">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="BEFORE_PARSE"/>
            <xsd:enumeration value="BEFORE_CONVERSION"/>
            <xsd:enumeration value="ON_ERROR"/>
            <xsd:enumeration value="VALIDATE"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="eventType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="CHUNK"/>
            <xsd:enumeration value="DOWNLOAD"/>
            <xsd:enumeration value="ERROR"/>
            <xsd:enumeration value="FINISH"/>
            <xsd:enumeration value="START"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="errorStrategy">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="CALL_SCRIPT"/>
            <xsd:enumeration value="IGNORE"/>
            <xsd:enumeration value="STOP"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="status">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="DONE"/>
            <xsd:enumeration value="DONE_WITH_ERRORS"/>
            <xsd:enumeration value="DOWNLOADING"/>
            <xsd:enumeration value="ERROR"/>
            <xsd:enumeration value="NOT_STARTED"/>
            <xsd:enumeration value="RUNNING"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:simpleType name="errorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="CONVERT_ERROR"/>
            <xsd:enumeration value="SERVICE_ERROR"/>
        </xsd:restriction>
     </xsd:simpleType>
    <xsd:complexType name="importError">
        <xsd:sequence>
            <xsd:element name="errorType" type="errorType" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="lineNumber" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="bean" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="message" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="exceptionClass" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="fielddto">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="fieldType" type="fieldType" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="start" type="xsd:long" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="size" type="xsd:long" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="maskPattern" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="hookdto">
        <xsd:sequence>
            <xsd:element name="hookFunction" type="hookFunction" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="script" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="layoutdto">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="description" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="fileFormat" type="fileFormat" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="errorStrategy" type="errorStrategy" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="delimiter" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="skipLines" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <!-- collection wrapper for fields -->
            <xsd:element name="fields" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="item" type="fielddto" minOccurs="1" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <!-- collection wrapper for hooks -->
            <xsd:element name="hooks" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="item" type="hookdto" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="importReport">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="startTime" type="xsd:dateTime" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="endTime" type="xsd:dateTime" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="uri" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="beanClass" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="serviceClass" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="layout" type="layoutdto" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="sucessCount" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="errorsCount" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="filteredCount" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="skippedCount" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <!-- collection wrapper for importErrors -->
            <xsd:element name="importErrors" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="item" type="importError" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="exportEventStatus">
        <xsd:sequence>
            <xsd:element name="importerId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="eventType" type="eventType" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="recordCount" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="importEventStatus">
        <xsd:sequence>
            <xsd:element name="importerId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="eventType" type="eventType" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="status" type="status" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="errorMessage" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="recordCount" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="importReport" type="importReport" minOccurs="0" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="exportConfig">
        <xsd:sequence>
            <xsd:element name="uri" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="layout" type="layoutdto" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="async" type="xsd:boolean" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="errorStrategy" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="importConfig">
        <xsd:sequence>
            <xsd:element name="uri" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="layout" type="layoutdto" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="async" type="xsd:boolean" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="batchSize" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="errorStrategy" type="errorStrategy" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="dependency">
        <xsd:sequence>
            <xsd:element name="domain" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="service" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
            <xsd:element name="version" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="uuid">
        <xsd:restriction base="xsd:string">
        	<xsd:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
        </xsd:restriction>
     </xsd:simpleType>
    
    <!-- Message payload elements for signals -->
    
    <!-- Message input/output elements for commands -->
    <xsd:element name="retrieveFuncionario">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="updateFuncionario">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="importFuncionario">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="importConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="importFuncionarioOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="importJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="exportFuncionario">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="exportConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="exportFuncionarioOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="exportJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createMergeMaquina">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="getPeca">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="status" type="statusPeca" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="getPecaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for peca -->
                <xsd:element name="peca" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="peca" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="updateMergeMaquina">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="exportRegistroProducao">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="exportConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="exportRegistroProducaoOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="exportJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="exportPeca">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="exportConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="exportPecaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="exportJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createBulkFuncionario">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for entities -->
                <xsd:element name="entities" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="funcionario" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createBulkFuncionarioOutput">
        <xsd:complexType>
            <xsd:sequence>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createBulkRegistroProducao">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for entities -->
                <xsd:element name="entities" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="registroProducao" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createBulkRegistroProducaoOutput">
        <xsd:complexType>
            <xsd:sequence>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createMergeFuncionario">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="importRegistroProducao">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="importConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="importRegistroProducaoOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="importJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="getMetadata">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="metadataFormat" type="xsd:string" minOccurs="0" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="getMetadataOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="metadata" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="retornaRegistroProducao">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="retornaRegistroProducaoOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for retorno -->
                <xsd:element name="retorno" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="recordRegistroProducao" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="updatePeca">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="deleteFuncionario">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="updateMergeRegistroProducao">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="retrieveRegistroProducao">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createMergeRegistroProducao">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="finalizar">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="finalizarOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="retorno" type="retornoAtualizarStatus" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="listMaquina">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="offset" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="size" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="orderBy" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="filter" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <!-- collection wrapper for displayFields -->
                <xsd:element name="displayFields" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="listMaquinaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for contents -->
                <xsd:element name="contents" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="maquina" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createPeca">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="retornaIdFuncionario">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="username" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="retornaIdFuncionarioOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="nome" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="id" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="retrievePeca">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="helloWorld">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="who" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="helloWorldOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="helloWorldMessage" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="deleteMaquina">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="importMaquina">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="importConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="importMaquinaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="importJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="exportMaquina">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="exportConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="exportMaquinaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="exportJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="mudarStatusPeca">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="status" type="statusPeca" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="mudarStatusPecaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="retorno" type="retornoAtualizarStatus" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="retrieveMaquina">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="updateRegistroProducao">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="updateMaquina">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="listFuncionario">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="offset" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="size" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="orderBy" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="filter" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <!-- collection wrapper for displayFields -->
                <xsd:element name="displayFields" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="listFuncionarioOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for contents -->
                <xsd:element name="contents" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="funcionario" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="odata">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="relatorio">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="dataInicio" type="xsd:dateTime" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="dataFinal" type="xsd:dateTime" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="tipoRelatorio" type="tipoRelatorio" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="turno" type="turnoFuncionario" minOccurs="0" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <!-- collection wrapper for funcionario -->
                <xsd:element name="funcionario" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <!-- collection wrapper for maquina -->
                <xsd:element name="maquina" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <!-- collection wrapper for codigoDesenho -->
                <xsd:element name="codigoDesenho" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="relatorioOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for retorno -->
                <xsd:element name="retorno" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="retornoRelatorio" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createBulkPeca">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for entities -->
                <xsd:element name="entities" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="peca" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createBulkPecaOutput">
        <xsd:complexType>
            <xsd:sequence>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createFuncionario">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="listPeca">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="offset" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="size" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="orderBy" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="filter" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <!-- collection wrapper for displayFields -->
                <xsd:element name="displayFields" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="listPecaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for contents -->
                <xsd:element name="contents" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="peca" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="listRegistroProducao">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="offset" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="size" type="xsd:long" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="orderBy" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <xsd:element name="filter" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
                <!-- collection wrapper for displayFields -->
                <xsd:element name="displayFields" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="listRegistroProducaoOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for contents -->
                <xsd:element name="contents" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="registroProducao" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="getDependencies">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="getDependenciesOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for dependencies -->
                <xsd:element name="dependencies" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="dependency" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createMaquina">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="createMergePeca">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="updateMergePeca">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="importPeca">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="config" type="importConfig" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="importPecaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="importJobId" type="xsd:string" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="deletePeca">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createRegistroProducao">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="updateMergeFuncionario">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="createBulkMaquina">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for entities -->
                <xsd:element name="entities" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="maquina" minOccurs="1" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="createBulkMaquinaOutput">
        <xsd:complexType>
            <xsd:sequence>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="getMaquinaAtiva">
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="getMaquinaAtivaOutput">
        <xsd:complexType>
            <xsd:sequence>
                <!-- collection wrapper for maquina -->
                <xsd:element name="maquina" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" type="maquina" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="deleteRegistroProducao">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:uuid" minOccurs="1" maxOccurs="1"  readOnly="false">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
