my_domain.my_service.helloWorld=NORMAL
my_domain.my_service.mudarStatusPeca=NORMAL
my_domain.my_service.getMaquinaAtiva=NORMAL
my_domain.my_service.getPeca=NORMAL
my_domain.my_service.relatorio=NORMAL
my_domain.my_service.retornaIdFuncionario=NORMAL
my_domain.my_service.finalizar=NORMAL
my_domain.my_service.retornaRegistroProducao=NORMAL
my_domain.my_service.serviceStarted=LOW
my_domain.my_service.notifyUserEvent=LOW
my_domain.my_service.getMetadata=NORMAL
my_domain.my_service.odata=NORMAL
my_domain.my_service.importPeca=NORMAL
my_domain.my_service.exportPeca=NORMAL
my_domain.my_service.importPecaEvent=LOW
my_domain.my_service.exportPecaEvent=LOW
my_domain.my_service.importFuncionario=NORMAL
my_domain.my_service.exportFuncionario=NORMAL
my_domain.my_service.importFuncionarioEvent=LOW
my_domain.my_service.exportFuncionarioEvent=LOW
my_domain.my_service.importMaquina=NORMAL
my_domain.my_service.exportMaquina=NORMAL
my_domain.my_service.importMaquinaEvent=LOW
my_domain.my_service.exportMaquinaEvent=LOW
my_domain.my_service.importRegistroProducao=NORMAL
my_domain.my_service.exportRegistroProducao=NORMAL
my_domain.my_service.importRegistroProducaoEvent=LOW
my_domain.my_service.exportRegistroProducaoEvent=LOW
my_domain.my_service.getDependencies=NORMAL
my_domain.my_service.createPeca=NORMAL
my_domain.my_service.createBulkPeca=NORMAL
my_domain.my_service.createMergePeca=NORMAL
my_domain.my_service.retrievePeca=NORMAL
my_domain.my_service.listPeca=NORMAL
my_domain.my_service.updatePeca=NORMAL
my_domain.my_service.updateMergePeca=NORMAL
my_domain.my_service.deletePeca=NORMAL
my_domain.my_service.createFuncionario=NORMAL
my_domain.my_service.createBulkFuncionario=NORMAL
my_domain.my_service.createMergeFuncionario=NORMAL
my_domain.my_service.retrieveFuncionario=NORMAL
my_domain.my_service.listFuncionario=NORMAL
my_domain.my_service.updateFuncionario=NORMAL
my_domain.my_service.updateMergeFuncionario=NORMAL
my_domain.my_service.deleteFuncionario=NORMAL
my_domain.my_service.createMaquina=NORMAL
my_domain.my_service.createBulkMaquina=NORMAL
my_domain.my_service.createMergeMaquina=NORMAL
my_domain.my_service.retrieveMaquina=NORMAL
my_domain.my_service.listMaquina=NORMAL
my_domain.my_service.updateMaquina=NORMAL
my_domain.my_service.updateMergeMaquina=NORMAL
my_domain.my_service.deleteMaquina=NORMAL
my_domain.my_service.createRegistroProducao=NORMAL
my_domain.my_service.createBulkRegistroProducao=NORMAL
my_domain.my_service.createMergeRegistroProducao=NORMAL
my_domain.my_service.retrieveRegistroProducao=NORMAL
my_domain.my_service.listRegistroProducao=NORMAL
my_domain.my_service.updateRegistroProducao=NORMAL
my_domain.my_service.updateMergeRegistroProducao=NORMAL
my_domain.my_service.deleteRegistroProducao=NORMAL
